# Generated by Django 2.1.5 on 2019-03-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_auto_20190306_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='translation',
            name='context_examples',
            field=models.CharField(default='Kamusta ka ba? -> How are you already?', max_length=500),
        ),
        migrations.AlterField(
            model_name='translation',
            name='downvotes',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='translation',
            name='origin_language',
            field=models.CharField(default='Filipino', max_length=250),
        ),
        migrations.AlterField(
            model_name='translation',
            name='origin_text',
            field=models.CharField(default='Kamusta', max_length=250),
        ),
        migrations.AlterField(
            model_name='translation',
            name='target_language',
            field=models.CharField(default='English', max_length=250),
        ),
        migrations.AlterField(
            model_name='translation',
            name='target_text',
            field=models.CharField(default='How are you', max_length=250),
        ),
        migrations.AlterField(
            model_name='translation',
            name='upvotes',
            field=models.IntegerField(default=100000),
        ),
    ]
