# Generated by Django 2.1.7 on 2019-03-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0004_auto_20190306_0822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(blank=True, default='Add a value here', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
